# To execute this docker compose yml file use `docker compose -f docker-compose-v3-beta-channel.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker compose -f docker-compose-v3-beta-channel.yml down`
services:
  chrome:
    image: selenium/node-chrome:beta
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - VNC_NO_PASSWORD=1
      - SE_NODE_MAX_INSTANCES=1
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4444:4444"
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
      - ./mongo-init:/docker-entrypoint-initdb.d:ro
  scraper-papeletas:
    build:
      context: ./scrapers
      dockerfile: Dockerfile
    depends_on:
      - chrome
      - mongodb
    command: ["python", "main.py", "dev"]
    ports:
      - "4567:4567"
  mcp-server:
    build:
      context: ./mcp-server
      dockerfile: Dockerfile
    depends_on:
      - scraper-papeletas
    command: ["python", "main.py"]
    ports:
      - "4200:4200"
volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
